### ISSUE TITLE
Import users & devices in mysql

### ISSUE THREAD

**Issue by pmlewisuk** [vitalidze/traccar-web#1002]
Hi

I want to upgrade to traccar-web, I'm using traccar 3.9 at the moment with some users and lots of devices.

when I upgrade it needs a new database, are the devices and user tables the same between both product so I can import those 2 tables?

Thanks

Mark

**Comment by vitalidze** [comment]
> when I upgrade it needs a new database, are the devices and user tables the same between both product so I can import those 2 tables?

They are similar, but not same. Moreover, some data, which is stored in `users` table in original database is stored in `user_settings` table in database being used by Traccar Web UI Mod. That's why you need to drop existing database before migration. 

Anyway, It is possible to compare fields in `users` and `devices` and then copy rows containing similar fields.

**Comment by pmlewisuk** [comment]
Perfect, Thanks
