### ISSUE TITLE
user configuration and usage.

### ISSUE THREAD

**Issue by akmal1999** [vitalidze/traccar-web#1022]
Hi,

Could someone help explain following in conjunction to device.

timeout(s) 300
idle when speed is <=0
min. idle time(s)

What does the above mean and usage.

many thanks in advance.

Regards,

**Comment by vitalidze** [comment]
First of all, please use search before posting your own question. For example, #597 already has similar questions.

> timeout(s) 300

Time to consider device "offline".

> idle when speed is <=0

Speed threshold to consider device "idle"/"stopped".

> min. idle time(s)

Time to pass with the above speed to consider device "stopped". For example when speed is zero for the 60 seconds, then device is considered "stopped", otherwise it is "idle" or "paused".
