### ISSUE TITLE
Log messages

### ISSUE THREAD

**Issue by lcatoni72** [vitalidze/traccar-web#1024]
Hello.
I'm trying to manage log messages in my server-side files (<..>/traccar/losg/???.log)
I am using the following code:

`Logger.getLogger(MyEditorDialog.class.getName()).log(Level.SEVERE, "TEST");`

I expect to find the message in this file, but the message is not produced.
I get two files produced in the logs `tracker-server.log` folder and `wrapper.log.20170113` but the message is not present.
how to produce server-side log message ?
thank you.

**Comment by vitalidze** [comment]
You need to configure JUL (java.util.logging) somehow to put your logs to some file. By default it just prints everything to stdout, which is then captured in wrapper.log files.

In your case `MyEditorDialog` is the class in UI. JUL will not print to server log if you invoke it in UI, instead of this the best it can do is to print something to web browser console, since the code is executed in javascript in browser. I think it will not work at all. If you need to put something into log file when some operation is executed in client, then you better add a service method called something like `log` say in `DataService` class, which will take specified message and log it with JUL.

**Comment by lcatoni72** [comment]
I'm already logging on to the browser console with` GWT.log ("TEST")`, the problem is that it is operating correctly with IDE running in super dev mode, but running the war as a Windows service, can not find any log message on my chrome console.
Thank you.

**Comment by vitalidze** [comment]
I think there is something with logging configuration. I recommend reading this: http://www.gwtproject.org/doc/latest/DevGuideLogging.html#Configuring_GWT_Logging

Also it may be possible that you haven't cleaned up web browser cache after installing updated `war` file and just running previous version.
