### ISSUE TITLE
BUG and Improvements

### ISSUE THREAD

**Issue by netluca1** [vitalidze/traccar-web#1039]
Hello Livtak compliments for good work.
I found some bugs and I would like to suggest improvements.

BUG:
Of preferences enlarge the square button obtained from the map and covered
Also on sensors should correct values; 
I use gps Teltonika and are present io
es. temp 30.00 / 3000; operator Wind / 22288; Voltage 12.55 / 1255; motion sensor 0/1 stop / moving; GSM signal 1 to 5 maybe write good, very good or symbol level

Configuring notifications
It should be the server to send notifications and do not enter an SMTP server for each user

message templates there are errors:
Went Offline: (wrong word)
The device '${geoFenceName}' went offline at '${positionTime}'
He entered the Geo-fence: (wrong word)
The device '${geoFenceName}' entered the Geo-fence '${eventTime}' to the '${maintenanceName}'
Released from Geo-fence: (wrong word)
The device '${geoFenceName}' is out of the Geo-fence '${eventTime}' to the '${maintenanceName}'
maintenance required: (wrong word)
'${GeoFenceName}' maintenance free '${positionAddress}'
excessive speed
'${GeoFenceName}' speed limit exceeded '${maintenanceName}'
Fermo: (wrong word)
The device '${geoFenceName}' Stopped at '${maintenanceName}'
On The Move: (wrong word)
The device '${geoFenceName}' started to move to the '${maintenanceName}'

the correct value is:
Went Offline:
The device '${deviceName}' is went offline at '${positionTime}'
He entered the Geo-fence:
The device '${deviceName}' is in of the Geo-fence '${geoFenceName}' to the '${eventTime}'
Released from Geo-fence:
The device '${deviceName}' is out of the Geo-fence '${geoFenceName}' to the '${eventTime}'
maintenance required:
'${deviceName}' maintenance free '${MaintenanceName}'
excessive speed:
'${deviceName}' speed limit exceeded '${positionAddres}
Fermo:
The device '${deviceName}' Stopped at '${positionTime}'
On The Move:
The device '${deviceName}' started to move to the '${positionTime}'

Improvements:
First, the key matter what is?
The filter should make the query not only the name, but the number of the device and make and model
We should be given more space as possible to the map by eliminating everything that does not serve
The left menu with the possibility of disappearance
The Archive menu below should disappear and you should be activated using a button located at the top on the bar to a different page with only a map and history data
Create a dashboard area that is displayed by pressing a button in the top bar
Menu sensors should be allowed to export I then import them into a new server.
In the maintenance menu the possibility of having a schedularizzazione concerning: stamp expires, insurance, incedio and Theft, Revision, Leasing, highways fee and then create a mediated alert or email alert.
In reports predict the function print or export to PDF or Exel
Improve the graphics in the report output
predict graphs of sensor consumption
Missing reports of the sensors; such as temperature, fuel, door contacts, maintenance, etc.

**Comment by vitalidze** [comment]
First of all thank you for spending time on writing this. However, I recommend to split up bugs/feature requests into several issues one-by-one.

Anyway, let's walk through all your points.

> Of preferences enlarge the square button obtained from the map and covered

Didn't understood what you meant.

> Also on sensors should correct values;
> I use gps Teltonika and are present io
es. temp 30.00 / 3000; operator Wind / 22288; Voltage 12.55 / 1255; motion sensor 0/1 stop / moving; GSM signal 1 to 5 maybe write good, very good or symbol level

This project is related with web UI, or "display" of data collected from devices. If you have some issues with data collected, then it's worth to submit them to the "backend" issue tracker: https://github.com/tananaev/traccar/issues

> Configuring notifications
> It should be the server to send notifications and do not enter an SMTP server for each user

You should read important notes in the official docs: http://traccar.litvak.su/features/notifications.html Basically, you don't need to configure SMTP server for each user. It is possible, but not necessary. It adds some flexibility, though.

> message templates there are errors:

I have just fixed these. Fix will be included in next release.

> First, the key matter what is?

Didn't understood.

> The filter should make the query not only the name, but the number of the device and make and model

It makes sense. Please create a new issue with this feature request.

> We should be given more space as possible to the map by eliminating everything that does not serve
> The left menu with the possibility of disappearance

This makes sense as well. Please create a separate feature request.

> The Archive menu below should disappear and you should be activated using a button located at the top on the bar to a different page with only a map and history data

This is quite subjective. I don't think it will be changed because people are used to the current Look-and-Feel.

> Create a dashboard area that is displayed by pressing a button in the top bar

This requires spending much time and effort. The requirements are too smooth. I don't think there is a big value on spending time on this.

> Menu sensors should be allowed to export I then import them into a new server.

Sounds too custom. What are you trying to achieve? If you have several servers, then probably it's better to copy sensors via DB queries.

> In the maintenance menu the possibility of having a schedularizzazione concerning: stamp expires, insurance, incedio and Theft, Revision, Leasing, highways fee and then create a mediated alert or email alert.

Well, you can create a separate feature request with this. I think it may be useful, but the priority will be quite low.

> In reports predict the function print or export to PDF or Exel

This was requested several times. It is planned.

> Improve the graphics in the report output

What's wrong with the graphics? It is based on the bootstrap. It is very simple and well-looking from my point of view. You get all the information ASAP.

> predict graphs of sensor consumption
> Missing reports of the sensors; such as temperature, fuel, door contacts, maintenance, etc.

These are also planned.
