### ISSUE TITLE
accessing position.other

### ISSUE THREAD

**Issue by EsajeeSolutions** [vitalidze/traccar-web#1127]
do i need to parse position.other every time ? can i access sensors data directly instead of position.other

**Comment by vitalidze** [comment]
Sensor data is stored in `position.other`. It is dynamic, that's why it is stored as JSON text (or XML text in older versions). So, yes, you need to parse it. From my memory newer versions of MySQL allow to run queries against JSON data stored in columns, you can try using this functionality. I haven't tried it myself though.
