### ISSUE TITLE
Device and Group Sharing Issue.

### ISSUE THREAD

**Issue by akmal1999** [vitalidze/traccar-web#1143]
Hi Vitaly,

1. Would you know why a device shared among multiple users would show under one user its shared and not anther another user that is equally shared.  5 device under one group shared among tow users. user 1 sees the device on the map however, user 2 can not see the device on the map. He can click on device the system pulls another coordinate as if the device is on the map but, is invisible.

2. another issue is we are getting coordinate tracking issue some of the devices create rundom lines where the actual individuals did not go to... What would be the issue and how can we fix it?

Many thanks.

**Comment by vitalidze** [comment]
First of all, please pay some respect and write my last name correctly at least. `Litvak` is my last name, `Vitaly` is the first name.

> Would you know why a device shared among multiple users would show under one user its shared and not anther another user that is equally shared. 5 device under one group shared among tow users. user 1 sees the device on the map however, user 2 can not see the device on the map. He can click on device the system pulls another coordinate as if the device is on the map but, is invisible.

This sounds like an issue with displaying devices on map. Since you are saying that there is a device in a list, but not on map, then this means there are no issues with access. I suggest to play with map zoom for the second user.

> another issue is we are getting coordinate tracking issue some of the devices create rundom lines where the actual individuals did not go to... What would be the issue and how can we fix it?

This is an issue with device. There may be many reasons for these and there are no common and/or simple solution. You need to find out why positions are reported this way. The easiest way will be to ask your device manufacturer for help. On your side you can look for a history of locations, compare server time and time reported by device.

**Comment by akmal1999** [comment]
Hi Vitaly, 

I am sorry for the name confusion. I corrected the issue. 

About the first question, we played with the map for hours however, the device is invisible but, when you click on the device it bring you on the map where the device is and we know the device is in that location however, we do not see the device on the map for the second user.  

I know it is not a permission issue as the user comes in the list however, do you think there should be an issue with the map here or something you suspect?

thanks,

**Comment by vitalidze** [comment]
> I know it is not a permission issue as the user comes in the list however, do you think there should be an issue with the map here or something you suspect?

It sounds like an issue with icon drawing. Have you tried changing mapping providers?

**Comment by akmal1999** [comment]
We have not made mapping provider changes. I tried to create another user and and see the same behaviour. tried to change the icon and it did not help.

can we share 1 device with many users at the same time and all of them are able to see it?

thanks for your answers.

**Comment by akmal1999** [comment]
Hi I would like to close this:

I found the issue, when creating the user... we were not enabling markers within the overlay. That was causing the icon not shown.

Closing this issue.
