### ISSUE TITLE
Problem Notification and Comand

### ISSUE THREAD

**Issue by ricardo2019** [vitalidze/traccar-web#1216]
Good morning.
I am new in traccar imolementación.
I congratulate you for such a great benefit.
I have some problems with the Litvak version:

1.- When generating the geo fences, it does not make the notifications automatically, a warning window does not appear as in the traccar version.
I can only enable notifications through Pusbullet.

2.- When sending commands to the GPS device TK 103A, send Stop vehicle will open a window in which indicates the following: "{}" not indicating anything ..... I close the window but I realized that if you send the command and stops the vehicle.
But the window should show some information as "Operation performed" for example.

Thank you.

**Comment by vitalidze** [comment]
Thank you for your interest.

> 1. When generating the geo fences, it does not make the notifications automatically, a warning window does not appear as in the traccar version.

The notification system is different and not related with the one from original traccar. You can read about geo-fences here: http://traccar.litvak.su/features/geofences.html About notification settings here: http://traccar.litvak.su/features/notifications.html

> 2.- When sending commands to the GPS device TK 103A, send Stop vehicle will open a window in which indicates the following: "{}" not indicating anything ..... I close the window but I realized that if you send the command and stops the vehicle.
> But the window should show some information as "Operation performed" for example.

You are more than welcome to implement the functionality that you are suggesting. Current approach is kind of technical: if you don't see any error then the message was sent to device. The "Operation performed" is incorrect here because sending a message does not mean that operation is performed.

**Comment by ricardo2019** [comment]
Dear.
The program and great.
I would like to see how it is possible to implement the alert system as in the Tracar version.
Use Pushbullet and it works perfect, but it limits the amount of notifications for which you have to buy the paid version and for account it is very expensive.
Any help on this topic?

Thank you.
