### ISSUE TITLE
High CPU load since latest release

### ISSUE THREAD

**Issue by rdosa** [vitalidze/traccar-web#136]
First of all thanks for the geozone development, that was the most wanted function for me.
However since last night after I updated the traccar-web.war, my VPS provider sent me an alert about the continuous high CPU load (because it violates the fair use policy). Switched back to one of the previous version of the war file, the CPU load fixed for its normal value. 
I use it on a 256MB OpenVz for months without any problem. 
Is there any suggestion to fix that?
Robert

**Comment by vitalidze** [comment]
I think this is caused by geo-fences processing. It scans all new positions every minute, which is most probably the reason for high CPU load. I don't see any other way of detecting geo-fence enter/exit events.

You may completely disable event recording in Settings >> Global menu by unchecking 'Event recording' box and saving changes.

**Comment by vitalidze** [comment]
Is there any update? May I close this issue?

**Comment by rdosa** [comment]
Sure: seems your suggestion (disable event recording) helped...
