### ISSUE TITLE
Rollback to original interface possibility

### ISSUE THREAD

**Issue by and12345** [vitalidze/traccar-web#192]
Hi, 

Great project and so happy to see your contribution to the community Litvak. Just some question here, 
    1. Is by using this interface will modify the database of traccar (can i rollback to original traccar interface smoothly)?
    2. Can i change the default port ?

**Comment by vitalidze** [comment]
1. This will modify database. However, changes are fully backward compatible with current version of web interface (which resides in https://github.com/tananaev/traccar-web). You can switch any time.
2. You can do this in configuration file of traccar. `http.port` should do the trick. (see https://www.traccar.org/configuration-file/ for all options). On linux systems if you want to use addresses below 1000 (like 80 or 443) most probably it will be restricted due to default security settings. The easiest way to work it out is to use reverse proxy (both apache and nginx support it, and both can be used with traccar).

**Comment by and12345** [comment]
Hi Vitalidze, 

thanks for the response. One more thing, do you have any plan on supporting send command via GPRS to GPS devices ?

**Comment by vitalidze** [comment]
I have it in a very long term plans (maybe in about of six months). I can see some activity on this topic in original project (https://www.traccar.org/forums/topic/sending-commands-to-devices-implementation/), so in theory my job will by just to integrate with their approach, which probably will happen much faster.

**Comment by vitalidze** [comment]
Do you have any other questions or I can close this issue?
