### ISSUE TITLE
New map provider request

### ISSUE THREAD

**Issue by rdosa** [vitalidze/traccar-web#203]
Hi,
is it possible to add an OpenSeaMap layer to the available maps provider list?
regards,
r

**Comment by peptoni** [comment]
In addition, I would vote for MapQuest Open, if possible, please.

**Comment by peptoni** [comment]
Also "toner" from http://maps.stamen.com would be nice.

**Comment by vitalidze** [comment]
Openseamap is already implemented in a branch. It was needed by single
user. But since someone needs it as well I will merge it to the upstream.

Will check possibility of including other map layers/providers when I come
back from vacation.

вторник, 30 июня 2015 г. пользователь peptoni написал:

> Also "toner" from http://maps.stamen.com would be nice.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/203#issuecomment-117258392
> .

## 

Kind regards, Vitaly Litvak

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/07/14/Snap-to-roads,-new-map-providers-and-translations.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Comment by rdosa** [comment]
Nice, thank you
