### ISSUE TITLE
Log file visualization error

### ISSUE THREAD

**Issue by webmst** [vitalidze/traccar-web#230]
Hi Vitaly,
I'm trying to display the log file from the settings menu, but the GUI is reporting "Tracker server log is not available. Looked at /logs/tracker-server.log, /logs/tracker-server.log, /tracker-server.log", that are all wrong pathnames as I'm storing logs in /var/log/traccar/tracker-server.logs.

It seems that your code is not acquiring the related value set in traccar.xml, as I can see the correct value at the entry key "logger.file".

Please have a check and tell me what to correct.

**Comment by vitalidze** [comment]
It looks up for logs under the folder, where traccar was started (usually '/opt/traccar'). There is a variable named `user.dir`, which contains such information:

``` java
        File workingFolder = new File(System.getProperty("user.dir"));
        File logFile1 = new File(workingFolder, "logs" + File.separatorChar + "tracker-server.log");
        File logFile2 = new File(workingFolder.getParentFile(), "logs" + File.separatorChar + "tracker-server.log");
        File logFile3 = new File(workingFolder, "tracker-server.log");
```

The thing is that web application is deployed to the traccar backend application and has no access to it's configuration file 'by design'. In theory it can try loading the configuration file by itself.

Looks like you have installed traccar to some non-standard location. Where it is actually installed? I suggest you to create symbolic link to the `logs` folder mentioned in warning message.

**Comment by webmst** [comment]
Hi Vitaly and thank you for the prompt answer.

I've installed traccar in /usr/local/traccar, logs are in /var/logs/traccar (this is standard for FreeBSD); so you may understand it's unexpected for me that you set the code to read the logfile in the application folder when there's a variabile trying to set the logfile to a different pathname in traccar.xml.

Of course, if you don't want to change this behaviour, I will actually create a symlink to the system log area.

Thanks again for the valuable assistance and congratulations for the development of traccar-web; I invite you to go on this way.

**Comment by vitalidze** [comment]
I understand your concern. I don't see a reliable way of accessing the configuration file because it's location is passed as the command line arguments and is lost after the config has been read. So the only way in current implementation of traccar backend is to guess the java class name, where the settings are stored. But this will always break when implementation changes (right now there is a 2.0 and 3.0 versions, both has configuration properties located in different java classes).
