### ISSUE TITLE
Location is incorrect

### ISSUE THREAD

**Issue by puneetshakya** [vitalidze/traccar-web#262]
Sir, I am using your web interface directly for tracking. But Android Traccar Client showing its location incorrect.  In status, location is updating properly by 20 seconds interval. How can it solve? And also plz help me to create tracking server on localhost?

**Comment by vitalidze** [comment]
If you mean my demo site then how can I find your tracker there? I want to check out the location that it sends. Usually such 'incorrect' locations are sent because you are indoors.

First of all you will need a server/computer with public IP address so your tracker can send data there through internet. Then you can find installation instructions for original traccar [here](https://www.traccar.org/documentation/) and then you may apply my UI mod by following [these instructions](http://traccar.litvak.su/installation.html).

**Comment by vitalidze** [comment]
Any update on this issue?
