### ISSUE TITLE
Map zoom freeze

### ISSUE THREAD

**Issue by ladikusz** [vitalidze/traccar-web#284]
Hi!

I have a strange issue after updating to the latest version. If i zoom in or zoom out on map (any layers), the zoom happens, but does not load the map to the adequate resolution, but the old map freezes. I can pan, but i can't zoom in / out anymore. Also i can't change layer. After a full page reload (F5), i can change layers, i can zoom - only once, again. Is there any trouble with the openlayers, or shall i debug on server side?

Thank you,
Viktor

**Comment by vitalidze** [comment]
Sounds like an issue with internet connection. You should check web browser console for error messages.

**Comment by ladikusz** [comment]
Tried the mobile site ( /m ) and it loads instantly, zoom works flawless, the desktop site still have the same problem. Also tried in incognito mode to avoid cache / cookie errors, no luck

**Comment by vitalidze** [comment]
Do you see any errors in browser console?

**Comment by ladikusz** [comment]
OpenLayers.js:670 Uncaught TypeError: Cannot read property 'resources' of undefined
traccar-0.js:3331 Uncaught TypeError: Cannot read property 'resources' of undefined

**Comment by vitalidze** [comment]
I confirm that it does not work for me on two of my servers. One is using very old version of the web UI, so it's not related with latest update. Looks like something is broken with integration between OpenLayers and OpenStreetMap.

**Comment by Jeferex** [comment]
I confirm the error too. it is happening in my 2 traccar instalation

**Comment by ladikusz** [comment]
Tried with Android 5.1, Chrome browser, and it works. On desktop tried with chrome, mozilla firefox, no luck. So definitely something with the openlayers, but only on desktop browser.

**Comment by vitalidze** [comment]
You mean it works in desktop version opened on android?

**Comment by ladikusz** [comment]
Yes, desktop version on android. Tried only openstreetmap, but will try with different layers.

**Comment by vitalidze** [comment]
That's weird. I will check this out when I have time.

**Comment by Jeferex** [comment]
It doesn't work for me in Android with chrome browser.

**Comment by ladikusz** [comment]
if i press the open desktop version, then i can zoom, pan OK. But if i select a vehicle, then zoom does not work. The animation after the pinch-zoom happens, but the zoom does not work. So basically does not work, just it seemed work :)

**Comment by Jeferex** [comment]
I found this https://github.com/openlayers/openlayers/issues/1461

how can we solve it @vitalidze ?

**Comment by vitalidze** [comment]
Looks like this is the case. The key is hard coded for now, so the only way to fix it is to make a release with updated key or even move it somewhere to the 'Global settings'. I will try to do it ASAP.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2015/10/15/fix-major-bug-with-maps-view.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions. Since the main download site is down you can download the `traccar-web.war` from the [release page on github](https://github.com/vitalidze/traccar-web/releases/tag/0.8.2).

Thank you very much for reporting this issue and guiding me with solution. I appreciate that.

**Comment by fitzy89** [comment]
Hi @vitalidze, I'm fairly new to this so apologies for my lack of knowledge. I'm running the neptune_theme branch as in #283 and I also have the same issue as mentioned here. Can I just build it again from source and will it have the fix for this issue included? Or will it take a while to apply it to the different branches? I'm not sure how github and branches work really so sorry to take too much of your time

**Comment by vitalidze** [comment]
I have already merged fix to this issue to `neptune_theme` branch. You need to pull changes from github or just delete your local repository and clone the github repository one more time.

**Comment by fitzy89** [comment]
Ok thankyou so much, just doing another clone now. Thanks for the fast and helpful support, wish all developers were as helpful as you.
