### ISSUE TITLE
PushAll notifications

### ISSUE THREAD

**Issue by 3err0** [vitalidze/traccar-web#288]
https://pushall.ru/

**Comment by vitalidze** [comment]
Well, if you want to implement it - I don't mind including it if you send me pull request. Otherwise, I think that pushbullet is much more popular thing, and I don't understand why should I use the 'pushall.ru' instead.

**Comment by 3err0** [comment]
A big plus PushAll that in addition to their regular clients that may come to my notice. Their service allows you to receive the same notification Telegram messenger , and in the browser, without any additions . Unlike Pushbullet, which I used before, but which requires the installation of a client to receive these notifications .

**Comment by 3err0** [comment]
And many mobile phone users without pre gapps (Google Play Services), client installation Pushbullet phone is not possible, because of the restrictions in the client requires the installation gapps

**Comment by vitalidze** [comment]
The only probably advantage I can see is the Telegram messaging support, I don't know how many people prefer this way of notifications. Pushbullet can help you setting up channels, you can receive notifications in browser, and so on. The next thing is the trust, I don't know how many people worldwide may trust some russian service.

I didn't understood the clause about installation because you need to install something to have the pushall.ru notifications. As for pushbullet you can receive notifications by email, which will work with any email client even without gapps.

**Comment by 3err0** [comment]
To work in the notification PushAll Telegram users only need to sign up on their website , and then adding them to the bot in the Telegram, except for the customer communications more , nothing needs to be installed . But I think to explain the principle of operation of the service is not a mandatory task in this topic.
And if you do not make it more difficult to implement in your supplement such a problem , I would have been very kind to you . And use these notifications certainly there , and not one.

Here is an example of a very simple PHP script that allows you easily send messages to PushAll, which after the distribution will go to recipients in the customers specified in the service. https://github.com/platx/pushall-php-client
