### ISSUE TITLE
How to display saved position (UTC) to local local zone

### ISSUE THREAD

**Issue by pierrot10** [vitalidze/traccar-web#300]
Good evening,

I am still playing with Traccar Web UI. It’s great.

I saved some position sent from my devise (Aduino/SIM808). My devise sent UTC time and I am located in Switzerland.
Then, from Setting->Preference I saved
(GMT+1:00) Europe/Zurich (CET)
into the time zone.

When I look for my Archive or when I check the last position, the time is not showing Local time but UTC as it has been sent.

What stand for the time zone in Settings->Preference?
How can display the UTC time in local time zone?

**Comment by vitalidze** [comment]
First of all, the timezone in Settings>>Preferences for now affects ONLY notifications, where it is used to format date/time for sending messages.

In web browser dates are always present in timezone, which is set up on the client system (the system where the browser is running). In database they are saved in unified format, which does not hold timezone, say it stores data in milliseconds since epoch. This means there is some mess with data in your database, you need to check what is saved there.

**Comment by vitalidze** [comment]
Any update on this issue?
