### ISSUE TITLE
Traccar Demo server - question

### ISSUE THREAD

**Issue by caslor** [vitalidze/traccar-web#308]
Hi 
i would like to ask something before i use the demo version to know if it will be out of policy 

As i am still looking for my own VPS  to upload the traccar ui   i was wondering if i could use the Demo server..

i want to track 15 devices (sailing boats)  for  5 races  per year  (every race last  one day  about 3-10 hours maximum )

it will be problem to use the demo version of traccar for that  for a while ?

Thanks in advance

ps : are any future plans for the Android client to have and the option of distance before sending data ? (in how many meters difference will start sending data of gps )

**Comment by vitalidze** [comment]
No problem, I don't mind if you (or anybody else) use it's for your own needs. I don't have any policy. But you need to be aware that it should be used at your own risk, the service may go down, may be restarted, unreliable, etc. and I will not be responsible if you lose some data because of that. Generally, I am restarting it only when I install upgrade, so there will be latest public available version there. However, there is a Digital Ocean (my VPS provider), which may have some issues.

> ps : are any future plans for the Android client to have and the option of distance before sending data ? (in how many meters difference will start sending data of gps )

I am not working on android client and have never worked on it. You better ask it on [forum](https://www.traccar.org/forums/forum/client/) or [issue tracker](https://github.com/tananaev/traccar-client-android). The only option that I am aware of and that could be of help in your task is the filtering on the backend side. You can set up the minimum number of meters between sequential positions coming from device so such position will be recorded to database (see `filter.distance` parameter in [configuration file docs](https://www.traccar.org/configuration-file/))

**Comment by vitalidze** [comment]
I think it's better to ask such questions by email (find it in my github profile). But I don't mind asking it here so everybody will know about the policy.

**Comment by rt3norio** [comment]
Thanks for keeping chats publically!

Em 10h07 Qua, 28/10/2015, Vitaly Litvak notifications@github.com escreveu:

**Comment by caslor** [comment]
Thanks :)  for the reply :)
