### ISSUE TITLE
[Feature request] Generic URL call for notifications?

### ISSUE THREAD

**Issue by matthuisman** [vitalidze/traccar-web#323]
It would be nice if you could enter in a URL and traccar-web would POST the notification data to.
This would open up a lot more possibilities for custom integration with other services.'
Maybe just POST the notification data in JSON format?

**Comment by vitalidze** [comment]
We have already discussed it here #153. The main thing is that in current implementation notification settings are set up on higher level (say by administrator or manager) and then sent to every user that have access to the device. I think that POSTing data to some URL expects one call instead of many calls per every user. Thus, this feature requires redesign of the notification mechanism in a way that every user may define not just the types of notifications he wants to receive but also the way (email, pushbullet, http), schedule and maybe even message format.

**Comment by matthuisman** [comment]
I'll close as duplicate :)
