### ISSUE TITLE
Save as CSV is not separated by commas

### ISSUE THREAD

**Issue by alvarengasv** [vitalidze/traccar-web#352]
The CSV file is actually separated by semicolon. If you open in excel the whole line is in a single column. 
If you edit in notepad and replace all ; with , it opens correctly in excel.

**Comment by gpproton** [comment]
This is also a major issue for me as i normally create analysis with excel files, i would love if the CVS files are displayed properly, i hope this is fixed soon.

Omonluimhen Godwin Peter

IT/Tracking
Officer | Beta Bridges Ltd

Date: Fri, 20 Nov 2015 04:48:38 -0800

**Comment by vitalidze** [comment]
The separator is actually locale-dependent because for example comma may be treated as decimal separator. Thus, I believe using ';' separator always is a more universal solution See this for more info: https://en.wikipedia.org/wiki/Comma-separated_values

You can try the solution from here: http://superuser.com/questions/180964/how-to-open-semicolon-delimited-csv-files-in-us-version-of-excel (like add `sep=;` at the beginning or rename file to .txt and then import it).

**Comment by alvarengasv** [comment]
Each of the column values are inside quotes so using comma as a column separator doesn't affect the comma when used as decimal separator. This will show up as 2 columns in excel not 3:
"13,50","50,75"

**Comment by vitalidze** [comment]
Most probably I will end with putting 'sep=;' at the beginning of output file.

**Comment by vitalidze** [comment]
I have made the following changes:

1) Field separator is now set up depending on current user's language/locale of the web UI. If locale uses ',' as the decimal separator then ';' will be used as field separator, ',' is used in all other cases.

2) At the beginning of the CSV file there will be a line indicating the field separator used for the whole file (`sep=;` or `sep=,`)

I believe this should cover all cases. I have checked it in MS Excel 2010 and it works just fine.

This is not yet included in the public available release, but it will be included in next version coming next week.

**Comment by gpproton** [comment]
Hi Litvak

I think it would be great to make reports open in a new tab and also be able to export the report to CSV file format.

Godwin Peter .O
IT /Tracking Officer | Beta Bridges Ltd
Godwin@Betabridges.com
+2348083353682

**Comment by vitalidze** [comment]
In future probably it will be possible to export reports to different formats: HTML (now implemented), XLS and PDF. As for opening in new tab, it is already implemented, there will be a 'preview' check box in the report profile. Will be included in next version.

Please don't post any further questions related with reports in this thread because it is related with exporting of archive data to CSV.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/11/24/Reports%E2%80%93preview,-stop-and-moving-events,-several-bugs-fixed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
