### ISSUE TITLE
No traccar-web.war file.

### ISSUE THREAD

**Issue by Smartie2016** [vitalidze/traccar-web#417]
I have read the installation instructions for updating my 3.2 version but I really can not find the tracer-web.war file in opt/traccar.

I also was not able to locate the tracer-web.war file anywhere on the system after a updatedb.

Has Traccar updated something?

**Comment by vitalidze** [comment]
Since version 3.x traccar does not contain the `traccar-web.war` file anymore. If you don't have it then just put it to the right place. Instructions work for both updating of your 3.x with installed `traccar-web.war` (when you want to update only the web UI mod, you will have it in place) and for the installation from scratch (you will not have it, so just put it to the place suggested in installation instructions).

**Comment by Smartie2016** [comment]
Ok, I'll try it.

Thanks

**Comment by Smartie2016** [comment]
It's working, also also made some mistakes in the xml file.

Perfect job, looks nice with great options.

Thanx
