### ISSUE TITLE
class file locked

### ISSUE THREAD

**Issue by wagnerdracha** [vitalidze/traccar-web#419]
Hi

I'm trying to edit the file:

C:\Users\Wagner Drachinski\IdeaProjects\traccar-web\target\traccar-web-0.10.2-SNAPSHOT\WEB-INF\classes\org\traccar\web\client\view\ArchivePanel.class

but Intellij 14 Ultimate does not leave, it seems that is locked and displays the message: Decompiled .class file, bytecode version: 51.0 (Java 7)

What can it be?

**Comment by vitalidze** [comment]
This is because you are trying to edit class-file, which is actually a file containing byte code - the result of compilation of the source file. You need to edit `.java` files and not `.class` files. Looks like you are missing some basic knowledge of java. I recommend to read something about programming in java, like 'getting started'. The official 'tutorials' is the very good place for the start: https://docs.oracle.com/javase/tutorial/

**Comment by wagnerdracha** [comment]
Ok, it's true. I was trying to edit the wrong file.

I had forgotten that this file can not be edited.

I apologize because I'm learning Java.

Thank you for your help
