### ISSUE TITLE
[Help wanted] Should update to traccar 3.3?

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#424]
Today traccar v3.3 was released. Has anyone made the transition? Apart from installing should I change anything to the database?

Thank you in advance for your response.

**Comment by mpele** [comment]
Is the current version of traccar-web compatible with 3.3?

**Comment by vitalidze** [comment]
Most probably it will work with same instructions. But I haven't got a time to test it. Will update this issue once I try it myself.

**Comment by warlockopy** [comment]
I am now just trying it, and the 1st problem I find is that the user table has something, not sure of what difference, but, cannot login to any account.

**Comment by vitalidze** [comment]
The web UI mod does not user `user` table, it manages it's own table named `users`. If you had some users in table `user` then you need to copy them manually.

**Comment by warlockopy** [comment]
so, what workaround can I do, since not even admin works. how do I copy and set password? sentences in SQL? how to create the password. Or is it available a default user password

**Comment by vitalidze** [comment]
The following administrator user credentials should be created at the first launch of the web UI mod:

username: admin
password: admin

To copy passwords you need to run an SQL query. Something like INSERT ... SELECT could work, but since most probably password is a hash, which is generated differently than in this project you will need to reset passwords as well.

**Comment by mpele** [comment]
I have clean installation of traccar 3.3. Should I folow instructions for
3.2?

**Comment by vitalidze** [comment]
Yeah. Try to follow same instructions.

вторник, 29 декабря 2015 г. пользователь mpele написал:

> I have clean installation of traccar 3.3. Should I folow instructions for
> 3.2?
> On Dec 28, 2015 9:02 PM, "Vitaly Litvak" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > The following administrator user credentials should be created at the
> > first launch of the web UI mod:
> > 
> > username: admin
> > password: admin
> > 
> > To copy passwords you need to run an SQL query. Something like INSERT ...
> > SELECT could work, but since most probably password is a hash, which is
> > generated differently than in this project you will need to reset
> > passwords
> > as well.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/vitalidze/traccar-web/issues/424#issuecomment-167643261
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/424#issuecomment-167746072
> .

## 

Kind regards, Vitaly Litvak

**Comment by warlockopy** [comment]
No, it was not created on 1st launch, now I am looking into the database.

**Comment by vitalidze** [comment]
@warlockopy do you see tables created by the web UI mod? There should be `users`, `geofences`, etc.

**Comment by warlockopy** [comment]
Now I can see the created tables, after re doing the instalation, but.
I get this error.
I am working over traccar 3.3
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
jvm 1    | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
jvm 1    | WrapperSimpleApp: 
jvm 1    | WrapperSimpleApp Error: Encountered an error running main:
jvm 1    | WrapperSimpleApp Error: liquibase.exception.DatabaseException: org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-190]
jvm 1    | WrapperSimpleApp Error:  at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:247)
jvm 1    | WrapperSimpleApp Error:  at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:151)
jvm 1    | WrapperSimpleApp Error:  at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:140)
jvm 1    | WrapperSimpleApp Error:  at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:160)
jvm 1    | WrapperSimpleApp Error:  at org.traccar.database.DataManager.<init>(DataManager.java:67)
jvm 1    | WrapperSimpleApp Error:  at org.traccar.Context.init(Context.java:121)
jvm 1    | WrapperSimpleApp Error:  at org.traccar.Main.main(Main.java:29)
jvm 1    | WrapperSimpleApp Error:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | WrapperSimpleApp Error:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
jvm 1    | WrapperSimpleApp Error:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jvm 1    | WrapperSimpleApp Error:  at java.lang.reflect.Method.invoke(Method.java:606)
jvm 1    | WrapperSimpleApp Error:  at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
jvm 1    | WrapperSimpleApp Error:  at java.lang.Thread.run(Thread.java:745)
jvm 1    | WrapperSimpleApp Error: Caused by: org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-190]
jvm 1    | WrapperSimpleApp Error:  at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
jvm 1    | WrapperSimpleApp Error:  at org.h2.message.DbException.get(DbException.java:168)
jvm 1    | WrapperSimpleApp Error:  at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:187)
jvm 1    | WrapperSimpleApp Error:  at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:167)
jvm 1    | WrapperSimpleApp Error:  at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
jvm 1    | WrapperSimpleApp Error:  at org.h2.engine.Database.getPageStore(Database.java:2450)
jvm 1    | WrapperSimpleApp Error:  at org.h2.engine.Database.open(Database.java:672)
jvm 1    | WrapperSimpleApp Error:  at org.h2.engine.Database.openDatabase(Database.java:269)
jvm 1    | WrapperSimpleApp Error:  at org.h2.engine.Database.<init>(Database.java:263)
jvm 1    | WrapperSimpleApp Error:  at org.h2.engine.Engine.openSession(Engine.java:65)
jvm 1    | WrapperSimpleApp Error:  at org.h2.engine.Engine.openSession(Engine.java:175)
jvm 1    | WrapperSimpleApp Error:  at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
jvm 1    | WrapperSimpleApp Error:  at org.h2.engine.Engine.createSession(Engine.java:136)
jvm 1    | WrapperSimpleApp Error:  at org.h2.engine.Engine.createSession(Engine.java:28)
jvm 1    | WrapperSimpleApp Error:  at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
jvm 1    | WrapperSimpleApp Error:  at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
jvm 1    | WrapperSimpleApp Error:  at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
jvm 1    | WrapperSimpleApp Error:  at org.h2.Driver.connect(Driver.java:72)
jvm 1    | WrapperSimpleApp Error:  at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:239)
jvm 1    | WrapperSimpleApp Error:  ... 12 more
jvm 1    | WrapperSimpleApp Error: Caused by: java.lang.IllegalStateException: The file is locked: nio:/opt/traccar/data/database.mv.db [1.4.190/7]
jvm 1    | WrapperSimpleApp Error:  at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
jvm 1    | WrapperSimpleApp Error:  at org.h2.mvstore.FileStore.open(FileStore.java:172)
jvm 1    | WrapperSimpleApp Error:  at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
jvm 1    | WrapperSimpleApp Error:  at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
jvm 1    | WrapperSimpleApp Error:  at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
jvm 1    | WrapperSimpleApp Error:  ... 27 more
wrapper  | <-- Wrapper Stopped
diego@diego-Aspire-E1-571 /opt/traccar $

**Comment by vitalidze** [comment]
Try to remove/comment out the following line in traccar configuration file:

``` xml
    <entry key='database.changelog'>./database/db.changelog-master.xml</entry>
```

**Comment by warlockopy** [comment]
now it works, but does not connect to the web in 8082
check conf

**Comment by warlockopy** [comment]
here config file attached

2015-12-29 11:37 GMT-03:00 Vitaly Litvak notifications@github.com:

**Comment by vitalidze** [comment]
Are there any errors in `wrapper.log` file?

**Comment by warlockopy** [comment]
STATUS | wrapper  | 2015/12/29 16:10:39 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2015/12/29 16:10:39 | Java Service Wrapper Community Edition 64-bit 3.5.27
STATUS | wrapper  | 2015/12/29 16:10:39 |   Copyright (C) 1999-2015 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/12/29 16:10:39 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/12/29 16:10:39 | 
STATUS | wrapper  | 2015/12/29 16:10:40 | Launching a JVM...
INFO   | jvm 1    | 2015/12/29 16:10:40 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/12/29 16:10:40 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2015/12/29 16:10:40 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
INFO   | jvm 1    | 2015/12/29 16:10:41 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @772ms
INFO   | jvm 1    | 2015/12/29 16:10:41 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> z8kfsx9d1ucsp9orl0660|6ae56499, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.h2.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> z8kfsx9d1ucsp9orl0660|6ae56499, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:h2:/opt/traccar/data/database, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=*****_, password=**_***}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
INFO   | jvm 1    | 2015/12/29 16:11:11 | [C3P0PooledConnectionPoolManager[identityToken->z8kfsx9d1ucsp9orl0660|6ae56499]-HelperThread-#1] WARN com.mchange.v2.resourcepool.BasicResourcePool - com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@4495f88b -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
INFO   | jvm 1    | 2015/12/29 16:11:11 | org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-190]
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.message.DbException.get(DbException.java:168)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:187)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:167)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Database.getPageStore(Database.java:2450)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Database.open(Database.java:672)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Database.openDatabase(Database.java:269)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Database.<init>(Database.java:263)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Engine.openSession(Engine.java:65)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Engine.openSession(Engine.java:175)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Engine.createSession(Engine.java:136)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Engine.createSession(Engine.java:28)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.Driver.connect(Driver.java:72)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
INFO   | jvm 1    | 2015/12/29 16:11:11 | Caused by: java.lang.IllegalStateException: The file is locked: nio:/opt/traccar/data/database.mv.db [1.4.190/7]
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.FileStore.open(FileStore.java:172)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   ... 23 more
INFO   | jvm 1    | 2015/12/29 16:11:11 | [C3P0PooledConnectionPoolManager[identityToken->z8kfsx9d1ucsp9orl0660|6ae56499]-HelperThread-#1] WARN com.mchange.v2.resourcepool.BasicResourcePool - Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@4aaf32dc is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests.
INFO   | jvm 1    | 2015/12/29 16:11:11 | [C3P0PooledConnectionPoolManager[identityToken->z8kfsx9d1ucsp9orl0660|6ae56499]-HelperThread-#1] WARN com.mchange.v2.resourcepool.BasicResourcePool - com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@1618346a -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
INFO   | jvm 1    | 2015/12/29 16:11:11 | org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-190]
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.message.DbException.get(DbException.java:168)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:187)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:167)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Database.getPageStore(Database.java:2450)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Database.open(Database.java:672)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Database.openDatabase(Database.java:269)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Database.<init>(Database.java:263)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Engine.openSession(Engine.java:65)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Engine.openSession(Engine.java:175)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Engine.createSession(Engine.java:136)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Engine.createSession(Engine.java:28)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.Driver.connect(Driver.java:72)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
INFO   | jvm 1    | 2015/12/29 16:11:11 | Caused by: java.lang.IllegalStateException: The file is locked: nio:/opt/traccar/data/database.mv.db [1.4.190/7]
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.FileStore.open(FileStore.java:172)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   ... 23 more
INFO   | jvm 1    | 2015/12/29 16:11:11 | [C3P0PooledConnectionPoolManager[identityToken->z8kfsx9d1ucsp9orl0660|6ae56499]-HelperThread-#1] WARN com.mchange.v2.resourcepool.BasicResourcePool - Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@4aaf32dc is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests.
INFO   | jvm 1    | 2015/12/29 16:11:11 | [C3P0PooledConnectionPoolManager[identityToken->z8kfsx9d1ucsp9orl0660|6ae56499]-HelperThread-#0] WARN com.mchange.v2.resourcepool.BasicResourcePool - com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@41d1d49d -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
INFO   | jvm 1    | 2015/12/29 16:11:11 | org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-190]
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.message.DbException.get(DbException.java:168)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:187)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:167)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Database.getPageStore(Database.java:2450)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Database.open(Database.java:672)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Database.openDatabase(Database.java:269)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Database.<init>(Database.java:263)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Engine.openSession(Engine.java:65)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Engine.openSession(Engine.java:175)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Engine.createSession(Engine.java:136)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.Engine.createSession(Engine.java:28)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.Driver.connect(Driver.java:72)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
INFO   | jvm 1    | 2015/12/29 16:11:11 | Caused by: java.lang.IllegalStateException: The file is locked: nio:/opt/traccar/data/database.mv.db [1.4.190/7]
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.FileStore.open(FileStore.java:172)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
INFO   | jvm 1    | 2015/12/29 16:11:11 |   ... 23 more
INFO   | jvm 1    | 2015/12/29 16:11:11 | [C3P0PooledConnectionPoolManager[identityToken->z8kfsx9d1ucsp9orl0660|6ae56499]-HelperThread-#0] WARN com.mchange.v2.resourcepool.BasicResourcePool - Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@4aaf32dc is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests.
INFO   | jvm 1    | 2015/12/29 16:11:12 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - jetty-9.2.14.v20151106
INFO   | jvm 1    | 2015/12/29 16:11:12 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@48e9afa1{/api,null,AVAILABLE}
INFO   | jvm 1    | 2015/12/29 16:11:13 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet

**Comment by vitalidze** [comment]
This means you have another instance already running, which blocks your h2 database. Try to stop service, kill all `java` processes and run service again.

**Comment by warlockopy** [comment]
Ok. Now it works, but with the same error, cannot loggin nor register

**Comment by vitalidze** [comment]
Do you have any records in `users` table in your database?

**Comment by warlockopy** [comment]
1   admin   admin   D33DCA55ABD4CC5BC76F2BC0B4E603FE2C6F61F4C1EF2D47    000000000000000000000000000000000000000000000000    false   true    osm en  km  kmh 0.0 0.0 0   true    false                       false       false                   1

**Comment by vitalidze** [comment]
It does not look like it is a `users` table. Probably it's `user` (without **s** at the end).

**Comment by warlockopy** [comment]
it is "users", the v3.3 has the table just like it, what happens if I delete?

**Comment by vitalidze** [comment]
It will be re-created after restart

**Comment by vitalidze** [comment]
Actually you can just truncate it and then start service. It should add `admin` user with `admin` password.

**Comment by warlockopy** [comment]
OK, now it works, steps done are this.
on folder /opt/traccar/data
- sudo chmod 777 database.mv.db

into sql workbench
- drop table users;

on folder /opt/traccar/data
- sudo /opt/traccar/bin/traccar restart

**Comment by vitalidze** [comment]
Thank you. I will consider these when I come to the updating of installation instructions.

**Comment by antoniopaisfernandes** [comment]
Leaving 777 perms on the database file is not a very good practice :)
If adding to the installation instructions, please consider reverting to more tighten permissions.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/02/09/Minor-bugfix-release-and-support-of-traccar-v3.3.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
