### ISSUE TITLE
Different User Location due to GPS signal though at same place

### ISSUE THREAD

**Issue by abhishekricky** [vitalidze/traccar-web#426]
Hi,

I am seeing if user is at same location, there is deviation in location . The user at same place for around 2 hours and below is the screenshot 

![image](https://cloud.githubusercontent.com/assets/5213928/12008911/3b16dc36-ac85-11e5-9ec2-307e2a03f6fb.png)

**Comment by vitalidze** [comment]
This is how GPS works on your device. Traccar has a possibility to filter locations, which are very close to each other. Or what is your question?

**Comment by abhishekricky** [comment]
Well My question how to avoid such deviations and filter location what should I use to show in proper format . I tried to filter it but nt able to decode and plus Snap to Road when i select all points are removed

**Comment by vitalidze** [comment]
The only thing you can do in traccar is set up positions filter by distance in configuration file. But in this case there will be no positions since some time, i.e. you will see the time when you stopped or entered the building, etc. Snap-to-roads has nothing to do with this, moreover right now there is a limitation of 100 points in a track for the function to work (track should not contain more than 100 points).

Generally, this is how GPS works inside of buildings. Basically, the accuracy can be up to 10-15 meters. Probably it's better to read some documentation about your device and look up for some settings there.

**Comment by abhishekricky** [comment]
Can you explain further about 100 points in a track . I see in Preference there is option of "Time stamps print interval:" and "Trace recording interval:"

**Comment by vitalidze** [comment]
This is related to the 'snap-to-roads' function only. The limitation comes from the third-party data provider.
