### ISSUE TITLE
How many devices can track  

### ISSUE THREAD

**Issue by panditji** [vitalidze/traccar-web#435]
Hi  vitalidze 
My question is that  How many devices can track  via your platform  http://d.traccar.litvak.su.

**Comment by vitalidze** [comment]
For now I don't limit the number of devices because demo server runs just fine with current amount of data. Probably if it will start lagging then I will create some limitation.

Please note that the demo server's main goal is to demonstrate functionality provided by the web UI mod. If you want to use it for other needs I am not responsible for anything related with that usage, in the mans of data loss, instability, corruption, etc. Also I can restart the server at any time.

**Comment by panditji** [comment]
Thanks for reply 
If i  track  a device's on my server then how many devices can track http://pro......:8082

**Comment by vitalidze** [comment]
There is no limitation in the software. It is limited only to your hardware resources. Basically the backend service (the one which collects data from devices) is very lightweight, you can track thousands of devices on a minimal hardware (like smallest instance on Digital Ocean with 512MB of RAM). I cannot say same for the front end because I don't have an experience with thousands of devices and I haven't done such testing.

**Comment by panditji** [comment]
Thanks a lot vitalidze  for  share your knowledge   i have some personal query that i'ill  ask  on mail
