### ISSUE TITLE
WARNING: Unable to find permissions manager

### ISSUE THREAD

**Issue by cwworth** [vitalidze/traccar-web#453]
I get the following in the service wrapper log

```
INFO   | jvm 1    | 2016/01/07 19:23:15 | Jan 07, 2016 7:23:15 PM org.traccar.web.server.model.MethodCallLogger invoke
INFO   | jvm 1    | 2016/01/07 19:23:15 | INFO: Login 'admin'
INFO   | jvm 1    | 2016/01/07 22:32:08 | Jan 07, 2016 10:32:08 PM org.traccar.web.server.model.BackendRefresher refreshWithReflection
INFO   | jvm 1    | 2016/01/07 22:32:08 | WARNING: Unable to find permissions manager
```

I believe this is possibly the cause of some issues I am having with trying to share groups of devices with users and also with managers not seeing any users when trying to share a device with a user.

I see the same issue on both my server which has the pre-built traccar-web.war and on my development machine on which I have built the war file from source using the build instructions you provided.

Both machines are Ubuntu 14.04 , with traccar 3.2 and using OpenJDK version 1.7.0_91

Otherwise I find it an excellent improvement on the stock traccar

**Comment by vitalidze** [comment]
This is just a warning. Please ignore it. It has nothing to do with permissions of the web UI mod.

Some clarification: When you deploy the `traccar-web.war` on the original traccar service there are actually two web services running: the API from original traccar and deployed web UI mod. Both services can check permissions, but they need to manage them in same way. On the API the permissions are cached, so I have written code in web UI mod, which tries to invalidate that cache. However, for now it will not work because permissions manager on the API (or on the "backend") does not start. It will be working only since 3.4 version of traccar. Probably I will remove/comment out this in next release.

**Comment by cwworth** [comment]
Whilst you say I can ignore it, is this WARNING linked to the problems I am having with SHARING?

On my system:
A Manager has the option to share a Device, but when trying to do so the list of target Users is empty.
A Manager has the option to share a Group, but when trying to do so the list of target Users is empty.
When a Manager tries to assign a device to a Group the drop-down list of Groups is empty.
An Administrator can appear to share a device with any other User, and share a Group of devices with any other User. However when the selected user accesses their account, only devices which have been shared on an individual device basis appear, and the group assigned devices do not.

As a system admin I would like to be able to give another non-admin user access to all devices in a specific group using the group share facility but it does not appear to work

**Comment by vitalidze** [comment]
Yes, you can ignore that warning.

> A Manager has the option to share a Device, but when trying to do so the list of target Users is empty.
> A Manager has the option to share a Group, but when trying to do so the list of target Users is empty.

This means your Manager does not have any underlying users. There is a brief description on this functionality in [features list](http://traccar.litvak.su/features/). Basically, manager manages users, which he created by himself and by all underlying managers. There is a link between a user and his manager.

> When a Manager tries to assign a device to a Group the drop-down list of Groups is empty.

This means your Manager does not have access to any group. The group should be shared to him somehow. You can find info here: http://traccar.litvak.su/features/groups.html

> However when the selected user accesses their account, only devices which have been shared on an individual device basis appear, and the group assigned devices do not.

If a user has access both to device and the group then it should definitely appear under that group when you logged in as that user. Otherwise, it's a bug. I don't quite understand your case, please give a more concrete example which does not work for you.

Actually even if user don't have access to group, but have access to device it still should appear in that group in devices view.

> As a system admin I would like to be able to give another non-admin user access to all devices in a specific group using the group share facility but it does not appear to work

There are no such function for now. The access to group of devices and devices entities is managed differently. So the only option is to give an access to that device one by one.

**Comment by cwworth** [comment]
I understand how you have created Groups and user management better now and that there is no fault with the application.
