### ISSUE TITLE
No changes when building traccer-web.war

### ISSUE THREAD

**Issue by zzyber** [vitalidze/traccar-web#456]
First of all, thanks for a superior tracking platform!

I´m struggling to make some changes to the interface and language files and i just can't figure out whats wrong. I have traccar ui up and running fine but if I change my language file located in src/main/resources/org/traccar/web/client/i18n and then make a new traccar-web.war no changes is being seen? 
Any ideas?

What I must get done is:
Background image login page
Some changes and additions to my language file
Change the blue color thru the whole system
Is there a guide or tutorial to help out here?

**Comment by ghost** [comment]
For background did you tried this ?

change the traccar-web home screen #265

**Comment by vitalidze** [comment]
> I´m struggling to make some changes to the interface and language files and i just can't figure out whats wrong. I have traccar ui up and running fine but if I change my language file located in src/main/resources/org/traccar/web/client/i18n and then make a new traccar-web.war no changes is being seen? 
> Any ideas?

Most probably you have built it incorrectly. You have to build it with maven: http://traccar.litvak.su/building.html 

There is another thing: if running from IDE (eclipse, idea, netbeans), then most probably you won't see changes in localisation files until you restart the web application. This is due to recent changes in localisation loading and generation. It is related only with localisation strings.

> Background image login page

As @waca98 suggested, please read #265 

> Some changes and additions to my language file

You can observe changes in recent commits, like this one https://github.com/vitalidze/traccar-web/commit/9160a87abe03b716cc2284704b44194b9a3c79f9 Generally, just update the necessary `.properties` file, rebuild the `traccar-web.war` and you are done.

> Change the blue color thru the whole system

This is a complex task. You can read about it here: https://docs.sencha.com/gxt-guides/3/concepts/appearance/Appearance_3.html and https://docs.sencha.com/gxt/3.x/ui/theme/GeneratingThemes.html

**Comment by zzyber** [comment]
Hi thanks for your feedback.
Yes im using Maven and now I made a test. I copied the english language file Messages.properties to replace my language file Messages_sv_SE.properties. Then i made ./maven package and moved the /target/traccar-web-0.10.3-SNAPSHOT.war to replace the /opt/traccar/traccar-web.war
Then started traccar but I still have the Swedish language active. 
I empty the cache in chrome but still the language is Swedish so I suppose Im working with the wrong language file?

**Comment by vitalidze** [comment]
Try to run `mvn clean package` to force the recompilation.

**Comment by zzyber** [comment]
Yes that feels like the solution I was looking for. Now i made a clean and got error compiling after, tried a couple of times, deleted the whole folder tramcar-web to start over downloading fresh but still same error so I rebooted the server just i case but still.......now I can't compile the code as I get failed with status 1. I will try this later from scratch and debug what is going on and keep you updated. In either case I would suggest to write the clean idea on the webb page under Building.

**Comment by zzyber** [comment]
Thanks for you help and I managed now to get it working.......i think. Its so random working, not working and because on fault in the beginning was "out of memory" I just added one more core and doubled the memory. I also stopped doing any changes when "failed" but just running it again and again until I get BUILD SUCCESS. One more thing, i reverted back to Java version 7 but I'm not sure that made any difference. So language done and now its time to dig into sencha theme.
