### ISSUE TITLE
Error when send command...

### ISSUE THREAD

**Issue by pjrastreadores** [vitalidze/traccar-web#497]
Hello , I have problem with the COMMAND Enviu mode, in which get this message below when I send any command to a range of trackers .

I'm using traccar 3.2

Request completed
Status: OK
Response
{"success":false,"error":"User not logged in - AccessControlException (BaseServlet:77 < CommandServlet:39 < *:18 < BaseServlet:53 < ...)"}
Fechar

**Comment by vitalidze** [comment]
Try using latest version of the Traccar Web UI Mod. Previously it was sending commands through the backend's API, but it didn't worked due to authentication issues. Now it uses API in a different way, which does not invoke authentication check on backend. Authentication is checked by the web UI mod itself.

**Comment by pjrastreadores** [comment]
Thanks for answering ! Where can I get this UI Mod Traccar Web ? And as I enter the traccar system with it?
