### ISSUE TITLE
API AddGeoFence Method

### ISSUE THREAD

**Issue by franiis** [vitalidze/traccar-web#512]
Hi, 
(I don't know Github etiquette, so I create separate post, for different problems. I hope it's ok).

It's similar problem to #509 and #511 (API and problem with @JsonIgnore attribute).

In this case AddGeoFence method works, but is quite unusable: GeoFence's field [description](https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/shared/model/GeoFence.java#L61), [points](https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/shared/model/GeoFence.java#L98), [type](https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/shared/model/GeoFence.java#L84) and [radius](https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/shared/model/GeoFence.java#L110) are marked with @JsonIgnore - API won't get this properties, so user via API can only create geofence with color and name. 
I think that unlocking this properties will fix this bug (works locally), but I don't know where else it is used.

(Maybe it's another problem)
I can also mention that Web Api seems to break, where then are few geofences with the same name. Choosing one, and then another can multiply them on list (for example I have 3 geofences "TEST" in database, but 4 on list in UI). It also can break user session or throw some error alerts.

Greetings
Piotr - franiis

**Comment by vitalidze** [comment]
> (I don't know Github etiquette, so I create separate post, for different problems. I hope it's ok).

This is perfect. Each issue should be submitted separately.

> In this case AddGeoFence method works, but is quite unusable: GeoFence's field description, points, type and radius are marked with @JsonIgnore - API won't get this properties, so user via API can only create geofence with color and name. 
> I think that unlocking this properties will fix this bug (works locally), but I don't know where else it is used.

This whole API was introduced to work with the mobile version of the web UI. Since it does not need to draw geo-fences, I preferred to minimize traffic and to not include additional data. Every latest position includes the geo-fences, where it is present. Probably for now it can be solved in a similar way as in #509 - enable one-way transition. I mean you can set it up to add/update geo-fence, but when loading geo-fences you won't have the points. Another way is to create a `MinimalGeoFence` object to be included in the latest position.

> (Maybe it's another problem)
> I can also mention that Web Api seems to break, where then are few geofences with the same name. Choosing one, and then another can multiply them on list (for example I have 3 geofences "TEST" in database, but 4 on list in UI). It also can break user session or throw some error alerts.

Well, this sounds like a bug. I haven't heard of it yet and also I cannot reproduce it. Please report it separately with more details.
