### ISSUE TITLE
traccar doesnt respect roads on showing drives and stops

### ISSUE THREAD

**Issue by houssamfarag** [vitalidze/traccar-web#532]
as you can see 

![traccar](https://cloud.githubusercontent.com/assets/17338209/13199960/b82dd762-d83e-11e5-950b-3d892ff55a1a.jpg)

how to make it respects roads and streets based on the map

**Comment by gsiotas** [comment]
Have you tried snap to roads function in the Archive tab
![screen shot 2016-02-21 at 02 11 36](https://cloud.githubusercontent.com/assets/10040858/13200002/77d52e7a-d840-11e5-9a34-7cdecb5edb32.png)

**Comment by houssamfarag** [comment]
it removes all pathway

**Comment by houssamfarag** [comment]
when i tried snap roads function the map shows nothing . i have to uncheck snap roads and reload to show the pathway again

**Comment by vitalidze** [comment]
'Snap to roads' function works through a third party provider, which has limit on the number of points in a track. So there are two possible reasons here:

1) Networking issue. Your web browser cannot connect to the third-party provider. This can be investigated with help of 'Developer tools' in chrome.

2) Track contains more than 100 points.

**Comment by houssamfarag** [comment]
I check for smaller duration less than 3 minutes with few points and snap to roads didnt show anything 

so it is somethings with web browser 

i will try another one and get back to you

**Comment by houssamfarag** [comment]
looks like it is the 100 points issue

any solution for this ?

**Comment by vitalidze** [comment]
This restriction comes from data provider. To solve it the only solution I can think of is to host your own server that will provide data. It is possible, server is open source and for the roads it uses free OpenStreetMap data.

**Comment by remrat** [comment]
Could you provide further details such as the name of the "Server" software.  Also, where in the WAR file we would need to edit to point to our local server?

I believe I have found the server software, OSRM.  I have it installed and running locally now.  What do I need to edit in TracCar to point to my local server?

**Comment by vitalidze** [comment]
Once you have installed [project-osrm](https://github.com/Project-OSRM/osrm-backend/wiki) and imported necessary data you need to:

1) Update URL in code here: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/client/controller/ArchiveController.java#L200

2) Rebuild the `traccar-web.war` with maven by following these instructions: http://traccar.litvak.su/building.html You may need to have a local maven installation and use `mvn` instead of `mvnw`.

Please note that version of project OSRM matters because if you use the latest version you will have same limitation hard coded. As far as I remember version 4.8.1 does not have such limitation, so I recommend to install it.

**Comment by remrat** [comment]
Excellent, Ill give it a try!
