### ISSUE TITLE
TimeStamp

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#534]
Hello,

Please what is timestamp  function for ?

![timestamps](https://cloud.githubusercontent.com/assets/15246747/13208206/8ef76688-d96a-11e5-865a-86fbc317cf94.jpg)

**Comment by vitalidze** [comment]
If you mean 'time stamps print interval' then this is for 'archive' and 'record trace' functions. It defines the period in minutes for the points which will have timestamp printed above them (the minute and hour in orange color). So for default 10 minutes you get timestamp printed for the point in every 10 minutes since the beginning of trace. Try to play with it and you will understand.

**Comment by thogo1977** [comment]
hello vitalidze and what is the meaning of Trace record intervall and what unit is it? Thanks Thomas

**Comment by vitalidze** [comment]
@thogo1977 the unit is minutes. I don't have any other words to explain it, besides in my previous comment. It's better to load some archived trace and look at the map. Some points will have timestamp printed above them. This setting controls frequency of such points.

**Comment by ghost** [comment]
As shown on the picture, what is the   default value  if trace recording interval is      blank ?

**Comment by vitalidze** [comment]
Trace recording interval is not limited in this case.
