### ISSUE TITLE
traccar 3.4 / traccar-web / raspberry Pi 2 with jessie lite -> OK !!!

### ISSUE THREAD

**Issue by flyjodel** [vitalidze/traccar-web#565]
hi

I freshly installed a traccar server on a rapsberry pi 2
OS : Raspbian version jessie-lite 4.1.18-v7+
java-8 sdk
traccar 3.4
all the mods to let traccar-webwar work properly

It works very well !
thanks

**Comment by sambote** [comment]
Hello
You have good luck, since 4 days I galley, impossible to make it work.

You'd be nice to tell me not to step the procedure because I am a newbie, and I absolutely need to install traccar on my raspi.
Kind regards

Sam

**Comment by flyjodel** [comment]
hi, where are you stuck ?
in big steps :
first of all, install raspbian, let's say Jessie
then install java
after that install traccar as mentionned in the documentation (very easy steps)
then install this web interface.
It should run smoothly without any problem. I've done it at least 10 times, on my raspi or VPS and no bigger issue. The main problem was to instruct my router to let the data go to the raspi, but in fact when you understand how it works, it's quite easy

**Comment by sambote** [comment]
Hello
My problem that I do not know linux functions, can you write me a line how to install Traccar.
I have installed Raspian Jessie, 
How do I install java? line of code
How do I install traccar? line of code
Then how to throw Traccar has each startup, due to power outages, so how do I install crontab, and how to start traccar? Line of code
Do you have what port open?
I think that with all this I could use Traccar grace âyour help

Thanks Sam

I think with all that I could use your help thanks to Traccar

**Comment by vitalidze** [comment]
> How do I install java? line of code

You can use google for that.

> How do I install traccar? line of code

Here is the documentation: https://www.traccar.org/documentation/

> Then how to throw Traccar has each startup, due to power outages, so how do I install crontab, and how to start traccar? Line of code

Use google for that.

> Do you have what port open?

Here is the list of devices with port numbers: https://www.traccar.org/devices/ For the web UI you will also need TCP port 8082 opened.

**Comment by sambote** [comment]
Hello
Thank you for your links, but they do not give me how to use lines of code, as for my part, I suck at linux
But I ended up install and launch TRACCAR with Java, but then while I opened a '5000 to 5500' port Beach nothing doesn't, no GPS point is indicated to my tracceur or my SmartPhone.
Remains to change the password because I read that you should not change it.
Thanks for your help.
Installation is the same on Windows Vista

**Comment by vitalidze** [comment]
> Thank you for your links, but they do not give me how to use lines of code, as for my part, I suck at linux

Then I guess you should start learning linux if you want to use it. Then, once you've learned something you should not have any issues with installation.

> But I ended up install and launch TRACCAR with Java, but then while I opened a '5000 to 5500' port Beach nothing doesn't, no GPS point is indicated to my tracceur or my SmartPhone.

You should look into log files to figure out what's wrong.

> Remains to change the password because I read that you should not change it.

I don't understand what it means. Why you can't change password?
