### ISSUE TITLE
How can I update from the version 25 Apr 2016 to the Version from 07 May 2016

### ISSUE THREAD

**Issue by retelder07** [vitalidze/traccar-web#686]
Dear Vitaly,

I have installed your version from 25 Apr 2016, now I see you published a new version at 07 May 2016.

Can you please explain me how can I make the update to the new version?

Thank you

**Comment by vitalidze** [comment]
If you don't update the backend (i.e. from 3.4 to 3.5) then it should be enough to simply replace your existing `traccar-web.war` with the new one and restart the service.

**Comment by retelder07** [comment]
Thanks, I make it like you said and it works.

When I start the service I get in the log every time

2016-05-20 18:25:14  INFO: Version: 3.5-SNAPSHOT
2016-05-20 18:25:16  **WARN: Table "SERVER" not found; SQL statement:**
SELECT \* FROM server; [42102-191] - JdbcSQLException (... < QueryBuilder:61 < *:131 < DataManager:456 < PermissionsManager:74 < ...)
2016-05-20 18:25:18  INFO: Starting server...

But all works good.

Here https://github.com/vitalidze/traccar-web/issues/651 you write 

vitalidze commented 21 days ago
You can safely ignore this warning.

Can you write me why I and other user get this error and why I can ignore it?

Thanks

**Comment by vitalidze** [comment]
> Can you write me why I and other user get this error and why I can ignore it?

This **warning** (it's not an error) comes from "backend", which tries to initialize it's own "Permission manager". Main reason for this is that there is no "server" table in the Traccar Web UI Mod and there are no such entity. I don't think it should be introduced to just hide that warning.

The "Permission manager" is used to check access to entities (devices, groups, positions, users, etc) within the "backend" server and since initalization failed noone will be able to access them through the "backend" API. 

However, when you use the web UI mod it does the entities management on it's own and does not use neither API nor "Permission manager" from the "backend". So, in this case you should be safe from unauthorized access to the "backend" API, Traccar Web UI Mod service will work just fine and backend will do it's job for posting positions to the database without any issues, since it does not require any permission check.
