### ISSUE TITLE
zoomToExtend in showTrack

### ISSUE THREAD

**Issue by antoniopaisfernandes** [vitalidze/traccar-web#70]
Hi,

I've noticed that zoomToExtend is commented in showTrack.

A nice feature would be to allow it to run when the user chooses to:
![image](https://cloud.githubusercontent.com/assets/6171197/5743021/403c519c-9c0e-11e4-80e3-cd6a85446447.png)

I'm having trouble linking all together (Archive, Map and this feature) without a lot of code "ugliness". Can you help (I see your code seems so clean)?

**Comment by vitalidze** [comment]
I would introduce a new class called `Track` in `client` package. It will store positions and their settings (line color, 'zoom to track', etc.). Then all methods that draw track in `MapPositionRenderer` and `MapController` should accept it instead of `List<Position>`. Then just take necessary settings and do the drawing work.

**Comment by antoniopaisfernandes** [comment]
Implemented in https://github.com/antoniopaisfernandes/traccar-web/commit/cbdb344275e728a85b810cef424be396c8486dbe
(still beta)

**Comment by vitalidze** [comment]
You got the idea right, I have added couple of comments.

**Comment by antoniopaisfernandes** [comment]
OK, will change.

**Comment by vitalidze** [comment]
Merged #76, written [news](http://traccar.litvak.su/2015/01/31/zoom-to-track-feature-and-devices-removal-bugfix.html), [article](http://traccar.litvak.su/features/zoom-to-track.html). Included in [latest public available version](http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://d.traccar.litvak.su).
