### ISSUE TITLE
The  marker does not move

### ISSUE THREAD

**Issue by Ruben1966** [vitalidze/traccar-web#716]
Dear Vitaly.

A few days ago the marker does not move from the position shown in the attached photo, please help solve this problem.
Best regards

Ruben
![traccar](https://cloud.githubusercontent.com/assets/15811174/15831373/896865ba-2bda-11e6-992b-1da5a15fa3c2.jpg)

**Comment by vitalidze** [comment]
Are you sure your device sends updated positions? Are you using latest version? (released on 04.06.2016)

**Comment by Ruben1966** [comment]
Vitaly.

Attached you will finda word documents  the server tracker logs.

I think i am using the lates version, but where i see 
[Tracker server logs.docx](https://github.com/vitalidze/traccar-web/files/301005/Tracker.server.logs.docx)
 the software version

**Comment by vitalidze** [comment]
I think I got it. The issue here is the wrong date `2027-01-04`. Some time ago your device has sent a position with this date and since all other newly received positions go before that date, the latest position does not get updated. You need to manually remove that position and set update latest position of your device with position with correct time. Then everything should be back to normal.

**Comment by Ruben1966** [comment]
Thank you very much.

I am going to update the device with position with correct time.

**Comment by Ruben1966** [comment]
Hi Vitaly.

The device is sending the right date and time: *HQ,355488020117586,V1,202808,,1405.99063,N,08711.77667,W,0.00,0,060616,FFFEFBFF#

I think,  I must  delete  the bad(2027-01-04 12:56:11) record in the tracar data base, but i do not know  how to do it

Can you help me please

**Comment by vitalidze** [comment]
You need to connect to your database with some database management tool, like MySQL Workbench if you are using MySQL. Then run `UPDATE` and `DELETE` queries for the positions. I guess, you can even do it without typing queries somehow.
