### ISSUE TITLE
blank maps in mobile version

### ISSUE THREAD

**Issue by gutcZHAW** [vitalidze/traccar-web#907]
Hello Vitaly

First of all thanks for your great work!

I work with a modified version of the release 3.5 with includes the following map layers:
Openstreetmap (free), Mapbox (API key), Google (API key), Bing (API key), swisstopo (domain registered at the provider)
All these maps work fine when i open the page as desktop version.
When I open the page as mobile version only the openstreetmap and the google map layer were displayed. When i open the mapbox layer as mobile version the page is blank and when i open the bing layer the openstreetmap layer will be displayed.

There were the following warnings when i load the map page as mobile version (independent of the selected map layer):
_Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys_
_Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required_

Do you have any idea how to fix this?

**Comment by vitalidze** [comment]
Well, it's hard to tell you what is wrong because as you said you have modified something to include all these layers. I guess if you are able to modify code to include them, then why can't you debug the code to figure out the reason of these issues? If you have added these layers to the desktop version, then you must write some code in javascript for the mobile version. The javascript part should be easier because usually all modern mapping providers have some examples in javascript.

> There were the following warnings when i load the map page as mobile version (independent of the selected map layer):
> Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
> Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required

This is because google maps javascript is always included into the web page. If you want to get rid of them you must remove the appropriate `<script>` tag from the HTML page. Another option is to get a valid API key from google.

**Comment by gutcZHAW** [comment]
Thanks a lot for your reply.

In fact i did only some small modifictations. The implementation of the maps were done by a guy who don't work in our company anymore. So im not that experienced as it seems in my question.

With your hint i found the javascript ("traccar-mobile.js") for the mobile version where only the following maps were handeled: Bing, OSM, Google, Mapquest, Stamen
So it's logical that only these maps are working in the mobile version.

Now I want to handle also the other maps in the mobile version. Is there an easy way to define all API keys only one time for both versions (mobile and desktop)?
The Bing API Key can be defined in the web UI, the Google API key is defined in "traccar.html" ([#754](https://github.com/vitalidze/traccar-web/issues/754)) and the Mapbox API key is defined in "MapView.java". 

I got valid API keys for Google, Bing and Mapbox but as it seems they were not used in the mobile version (Bing doesnt' work and the google API warning still appears).

Last but not least I should give Daniel Früh's (ZHAW switzerland) regards to you.

**Comment by vitalidze** [comment]
> With your hint i found the javascript ("traccar-mobile.js") for the mobile version where only the following maps were handeled: Bing, OSM, Google, Mapquest, Stamen
> So it's logical that only these maps are working in the mobile version.

Absolutely correct.

> Now I want to handle also the other maps in the mobile version. Is there an easy way to define all API keys only one time for both versions (mobile and desktop)?

There is no easy way because they are defined differently based on the mapping provider. For example, for google maps you need to put key into the `<script>` tag and for Bings Map you can put it during JavaScript object instantiation.

> I got valid API keys for Google, Bing and Mapbox but as it seems they were not used in the mobile version (Bing doesnt' work and the google API warning still appears).

Bing doesn't work due to #873, which is fixed in code, but is not included in public available release yet. For google maps you should use solution from #754, i.e. just update the `<script>` tag, which includes google maps javascript. It should be easy to find it both in mobile and desktop versions.

> Last but not least I should give Daniel Früh's (ZHAW switzerland) regards to you.

Thank you. Nice to know that you are his friend (and/or teammate). Hope he is doing well. Cheers!

**Comment by gutcZHAW** [comment]
Thank you a lot for your help!
After the implementation of the other maps in the desktop and mobile version there occured some other issues but finally it works fine.
He has a lot of work but hes doing well :)
Cheers
