### ISSUE TITLE
Snap to Road - error 0

### ISSUE THREAD

**Issue by xewonder** [vitalidze/traccar-web#937]
Good day,

When trying to use the "snap to road" feature I get the following error:

Error loading track snapped to roads (0)

the URL in global settings is 
https://router.project-osrm.org/match

any idea?

Thank you in advance

**Comment by vitalidze** [comment]
This is because demo server of Project OSRM was switched to a newer version of the API, which is not supported in current version of Traccar Web UI Mod. I have started developing support for a newer version, but it is not yet completed. 

As an option you can install older version of Project OSRM on your server and use it with current version of Traccar Web UI Mod.

See #830 for additional information.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/12/17/Bugfix-Release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
